language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ti4GapwUkzqKCnp8lkHtGsmfiJSIXoiBUKpmLGmr1wl9vvOfySnBYS8IkbIxgKQXZ2HKyY7SahiCiHKPmCKjL9HdzTCYUbCLvnVq/rsbLk9deUBYmgJ2rlhb9wQGR4VN37c/aqM1nIbDJSqNqzEXE2jvmkIv2NFUq7+gTsz4B2uqelozx4wJcBvkxr3J7UbH/7C5CCm36Ix3Z7Dz9oxfmY9eYaVeoM9we7o/oWdRWZmrf+Nejn47pAkmnOG0KC8SzRtuXAgtIfdYPuNC7RMDAgIG0inxCW2DH2dzT+5Zqhe97Gat2Pu+aIXyV3yHj1TX4sdoMvnnJGaxcDKCZxMrA+YdbX/FLS6AUbR2chjzs018uqpWX01nIh8Y8MV4P8pCQmkwixQ75Yqhtzyib9vAs4j0Kb59UWQdh0Tfoosj1DUAxFVTHvguQrXzuwKDUqJiV8qnzgWv/7W3PW6Pb4h4Y5uOzQ4+DamVk9iOexU+ZwXpptpn+So8sgHLhYZSAV0O42Z8JJdZthjOvVo9lvFzNum6xtpmgwjm1Dorl3zox4s5zh6IeUYryWc9skDEiP9QstGtHK9PGnE5Q3PW337ts8YKmIo+BNOlqDbG/nc58au054k8dyIm5TvHPgzMviaiIlBWtnhj7AjkLjkV4xHFas+XghrIgBAOUJ5GvuVq8Ak=
  app: immense-brushlands-16839
  on:
    repo: Kaleidics/team-node-project
