language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Lf8hPgbR2wd+L6ajxP88v3CfXix/dg6wzw01DoMvAuG9smO3XyN09WZayp5twLCW2mjZoSPx9ijZ5R6EmnJpelwPWPJNpNDGRCOfL70RW/PXNQsGnKL1gSFQJyOUqlaMkpWVgBd01936RGMAD1VXnX+HQXHHSUBQl5wpGstqtKIrJXPlXV5FMlhdqHda4NhQPr3cTJT4IuUhuMIH0dFtaML2UzD1J6uMOg6uzixDSJDDEvQZEfcbUQ6e+Jl1weaHTZhKArCPLIaanG+A+HXzxzChhmd13O9O0HgYv0H7IJC/asJC8+HXTrR686ty17z+ssk7e7nWRPbc5b5ZkKbON88lXIgBs6lgMhjRlEDKqj2D7+Cup2YM/dglTF8OTD6jGyGG/VL11hGtliVmmttuHsdCXSIZ8ScM04YQN2GWR6cQWiJNo5yeS817VQNA36t0HQZ3Uij9xM74jcTEdo6mGUEfgDhh0MbFf76iTLI3pepV1DQHUDi0m7HIU1L6y297+BeO1XJvVh03zbWcFsOoLfuUafBEMCsGKUL9HeTfAdSt6YaCA8PGTNjeVWjB7FuFF0GQzxr2ODK/5oW41omXCjlrPRzdrCghCMAncVNcnWAyMIXKtCsM0/+zBvOIC/O5chhro4m6/I1+f9PZl63TseNHEgv95lmlP+DwZptNfHw=
  app: team-node-project
  on:
    repo: Kaleidics/team-node-project
